package model;

// Generated 7 sept. 2015 15:10:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Courier generated by hbm2java
 */
@Entity
@Table(name = "courier", catalog = "ccisdb")
public class Courier implements java.io.Serializable {

	private Integer idCourier;
	private Distinataire distinataire;
	private Recepteur recepteur;
	private String objet;
	private Date date;
	private String type;
	private byte[] fichierJoint;

	public Courier() {
	}

	public Courier(Distinataire distinataire, Recepteur recepteur) {
		this.distinataire = distinataire;
		this.recepteur = recepteur;
	}

	public Courier(Distinataire distinataire, Recepteur recepteur,
			String objet, Date date, String type, byte[] fichierJoint) {
		this.distinataire = distinataire;
		this.recepteur = recepteur;
		this.objet = objet;
		this.date = date;
		this.type = type;
		this.fichierJoint = fichierJoint;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCourier", unique = true, nullable = false)
	public Integer getIdCourier() {
		return this.idCourier;
	}

	public void setIdCourier(Integer idCourier) {
		this.idCourier = idCourier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "distinataire_idDistinataire", nullable = false)
	public Distinataire getDistinataire() {
		return this.distinataire;
	}

	public void setDistinataire(Distinataire distinataire) {
		this.distinataire = distinataire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "recepteur_idRecepteur", nullable = false)
	public Recepteur getRecepteur() {
		return this.recepteur;
	}

	public void setRecepteur(Recepteur recepteur) {
		this.recepteur = recepteur;
	}

	@Column(name = "objet")
	public String getObjet() {
		return this.objet;
	}

	public void setObjet(String objet) {
		this.objet = objet;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "fichierJoint")
	public byte[] getFichierJoint() {
		return this.fichierJoint;
	}

	public void setFichierJoint(byte[] fichierJoint) {
		this.fichierJoint = fichierJoint;
	}

}
