package model;

// Generated 7 sept. 2015 15:10:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Departement generated by hbm2java
 */
@Entity
@Table(name = "departement", catalog = "ccisdb", uniqueConstraints = @UniqueConstraint(columnNames = "libelle"))
public class Departement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idDepartement;
	private String libelle;
	private Set<Service> services = new HashSet<Service>(0);

	public Departement() {
	}

	public Departement(String libelle) {
		this.libelle = libelle;
	}

	public Departement(String libelle, Set<Service> services) {
		this.libelle = libelle;
		this.services = services;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDepartement", unique = true, nullable = false)
	public Integer getIdDepartement() {
		return this.idDepartement;
	}

	public void setIdDepartement(Integer idDepartement) {
		this.idDepartement = idDepartement;
	}

	@Column(name = "libelle", unique = true, nullable = false, length = 45)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departement")
	public Set<Service> getServices() {
		return this.services;
	}

	public void setServices(Set<Service> services) {
		this.services = services;
	}

}
