package model;

// Generated 7 sept. 2015 15:10:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Distinataire generated by hbm2java
 */
@Entity
@Table(name = "distinataire", catalog = "ccisdb")
public class Distinataire implements java.io.Serializable {

	private Integer idDistinataire;
	private String raisonSocial;
	private String telephone;
	private String faxe;
	private String adresse;
	private String gradeDeResponsable;
	private Set<Courier> couriers = new HashSet<Courier>(0);

	public Distinataire() {
	}

	public Distinataire(String raisonSocial, String telephone, String faxe,
			String adresse, String gradeDeResponsable, Set<Courier> couriers) {
		this.raisonSocial = raisonSocial;
		this.telephone = telephone;
		this.faxe = faxe;
		this.adresse = adresse;
		this.gradeDeResponsable = gradeDeResponsable;
		this.couriers = couriers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDistinataire", unique = true, nullable = false)
	public Integer getIdDistinataire() {
		return this.idDistinataire;
	}

	public void setIdDistinataire(Integer idDistinataire) {
		this.idDistinataire = idDistinataire;
	}

	@Column(name = "raisonSocial", length = 45)
	public String getRaisonSocial() {
		return this.raisonSocial;
	}

	public void setRaisonSocial(String raisonSocial) {
		this.raisonSocial = raisonSocial;
	}

	@Column(name = "telephone", length = 45)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "faxe", length = 45)
	public String getFaxe() {
		return this.faxe;
	}

	public void setFaxe(String faxe) {
		this.faxe = faxe;
	}

	@Column(name = "adresse", length = 45)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "gradeDeResponsable", length = 45)
	public String getGradeDeResponsable() {
		return this.gradeDeResponsable;
	}

	public void setGradeDeResponsable(String gradeDeResponsable) {
		this.gradeDeResponsable = gradeDeResponsable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "distinataire")
	public Set<Courier> getCouriers() {
		return this.couriers;
	}

	public void setCouriers(Set<Courier> couriers) {
		this.couriers = couriers;
	}

}
