package model;

// Generated 7 sept. 2015 15:10:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Recepteur generated by hbm2java
 */
@Entity
@Table(name = "recepteur", catalog = "ccisdb")
public class Recepteur implements java.io.Serializable {

	private Integer idRecepteur;
	private Service service;
	private String nom;
	private String prenom;
	private Set<Courier> couriers = new HashSet<Courier>(0);

	public Recepteur() {
	}

	public Recepteur(Service service) {
		this.service = service;
	}

	public Recepteur(Service service, String nom, String prenom,
			Set<Courier> couriers) {
		this.service = service;
		this.nom = nom;
		this.prenom = prenom;
		this.couriers = couriers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idRecepteur", unique = true, nullable = false)
	public Integer getIdRecepteur() {
		return this.idRecepteur;
	}

	public void setIdRecepteur(Integer idRecepteur) {
		this.idRecepteur = idRecepteur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "service_idService", nullable = false)
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	@Column(name = "nom", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 45)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recepteur")
	public Set<Courier> getCouriers() {
		return this.couriers;
	}

	public void setCouriers(Set<Courier> couriers) {
		this.couriers = couriers;
	}
	
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return this.nom.toUpperCase()+" "+this.prenom.toLowerCase();
	}

}
